### PR TITLE
DE-1287 - Update axios dependency with latest

### PR DESCRIPTION
**Pull request by mkstix6**
Snyk raised security alert.

Update `axios` from `1.6.0` to `1.6.8` (latest).

## To review

- [ ] `npm i`

### Tests green:

- [ ] `npm test`
- [ ] `npm run test-integration`

### CODE REVIEW

**Comment by mkstix6** [comment]
> My guess would be that this is better but should double-check. It could be happenstance or intentional :thinking:.

I’m just upgrading `axios` and noticed the resolved registry is changing from the public registry to our ITV registry (my machine is pointed at).

Is fine? …or no?

Screenshot 2024-04-04 at 11 00 39

**Comment by juliomalves** [comment]
> > My guess would be that this is better but should double-check. It could be happenstance or intentional 🤔.
> 
> I’m just upgrading `axios` and noticed the resolved registry is changing from the public registry to our ITV registry (my machine is pointed at).
> 
> Is fine? …or no?

This repo should use the public npm registry, as it's public-facing.

**Comment by mkstix6** [comment]
> This repo should use the public npm registry, as it's public-facing.

Ok I will work out how to resolve this back to the Public npm registry.

**Comment by cactusa** [comment]
> > > My guess would be that this is better but should double-check. It could be happenstance or intentional 🤔.
> > 
> > 
> > I’m just upgrading `axios` and noticed the resolved registry is changing from the public registry to our ITV registry (my machine is pointed at).
> > Is fine? …or no?
> 
> This repo should use the public npm registry, as it's public-facing.

@juliomalves my understanding is that we are using ITV's registry by default because it serves as a caching layer for all our dependencies external or internal, so even if npm is down we have our registry to rely on. This is what I vaguely remember from conversations with @soundstep years ago.

**Comment by juliomalves** [comment]
> @juliomalves my understanding is that we are using ITV's registry by default because it serves as a caching layer for all our dependencies external or internal, so even if npm is down we have our registry to rely on. This is what I vaguely remember from conversations with @soundstep years ago.

That's all true, but this repo is public and non-ITV people do not have access to ITV's private npm registry so we have to use the public registry. This repo also does not use any ITV-specific dependencies so there's no need to use the private registry anyway.

**Comment by cactusa** [comment]
> > @juliomalves my understanding is that we are using ITV's registry by default because it serves as a caching layer for all our dependencies external or internal, so even if npm is down we have our registry to rely on. This is what I vaguely remember from conversations with @soundstep years ago.
> 
> That's all true, but this repo is public and non-ITV people do not have access to ITV's private npm registry so we have to use the public registry. This repo also does not use any ITV-specific dependencies so there's no need to use the private registry anyway.

@juliomalves Ah yes indeed, I missed the part about this repo being public, apologies.

**Comment by mkstix6** [comment]
Further thoughts:

1. Should I add a `CONTRIBUTE.md` file to note down some of this reasoning but worded carefully in a public facing way?
2. Do I need to manually bump the repo number?

**Review by Roberto14 — APPROVED** [review]
LGTM!

**Comment by Roberto14** [comment]
> Further thoughts:
> 
> 1. Should I add a `CONTRIBUTE.md` file to note down some of this reasoning but worded carefully in a public facing way?
> 2. Do I need to manually bump the repo number?
> 3. I guess at the end I just "Squash and merge" the PR, right?

Hey
About contributing, it should be another task so I won't worry with that for now. 
Regarding the publishing, you can use npm version and npm publish see more here (https://docs.npmjs.com/updating-your-published-package-version-number).
On 3. yep hit squash and merge.

**Review by emmapriceitv — APPROVED** [review]

**Pull request merged**
